dist: admission-webhook

env:
  global:
    - IMAGE_NAME=pkskubeflow/admission-webhook:v1.0.0-gaf96e4e3
    - CODE_TAG=v1.0
    
arch:
#  - amd64
  - arm64

services:
  - docker

before_install:
  - git clone -b ${CODE_TAG} --depth 1 https://github.com/kubeflow/kubeflow.git

script:
  - cd kubeflow/components/admission-webhook
  - docker build -t ${IMAGE_NAME} -f Dockerfile .
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PWD}
  - docker push ${IMAGE_NAME}
